operable/cog-book

- cog_book.adoc
- src/installation_guide/text.adoc
⚠️ Still a work in progress. Needs section linking and some notes and such.
> Install guide

- cog_book.adoc
- pygments-default.css
- src/bootstrapping_cog/text.adoc
- src/building_command_bundles/text.adoc
- src/bundle_configs/text.adoc
- src/command_environment_variables/text.adoc
- src/command_execution_rules/text.adoc
- src/commands_and_bundles/text.adoc
- src/configuring_password_resets/text.adoc
- src/installation_guide/text.adoc
- src/installing_and_managing_relays/text.adoc
- src/introducing_cog/text.adoc
- src/managing_bundles/text.adoc
- src/permissions_and_rules/text.adoc
- src/writing_a_command_bundle/text.adoc
- stylesheets/cog.css
Added two chapters from the Command Development section on http://docs.operable.io/v0.16
Bundle Configs
Command Environment Variables
> Command development

- src/reference/cog_server_configuration.adoc
> Document COG_BOOTSTRAP_CHAT_HANDLE variable

- src/writing_a_command_bundle/code/stats_command/config.yaml
- src/writing_a_command_bundle/text.adoc
just in case reader is really unfamiliar with Ruby?
> Add gem install instruction

- src/writing_a_command_bundle/code/stats_command/config.yaml
- src/writing_a_command_bundle/text.adoc
Also removed extra permissions in the config.yaml file... they were already present at the top.
> Minor edits for flow for Gemfile instructions

- src/installation_guide/text.adoc
Closing out tickets #44  and #46
> PR for #44 and #46

- cog_book.adoc
- src/reference/greenbar_tags.adoc
- src/templates/text.adoc
> Advanced greenbar usage

- cog_book.adoc
- src/appendices/chat_platforms.adoc
- src/appendices/designing_for_chatops.adoc
Additional notes about differing experiences for each chat platform
can be added here, as well.
> Add note about HipChat emoji and autolinking

- cog_book.adoc
- src/reference/command_output_tags.adoc
- src/returning_data_from_cog/text.adoc
Closes https://github.com/operable/cog/issues/1207
> Document command output tags

- src/commands_and_bundles/text.adoc
- src/writing_a_command_bundle/text.adoc
Per a discussion with a public community member, these issues were
discovered.
> Copy Editing + Updating of Links

- src/installation_guide/text.adoc
> Updates clone path for go-relay

- Dockerfile
- cog-book/source/conf.py
- themes/rtd/breadcrumbs.html
- themes/rtd/theme.conf
---
Links automatically take into account current branch name and directory structure
> Enable "Edit on GitHub" in page header

- style-guide/source/style_guide.rst
Converted the Style Guide to fit the Sphinx and reStructuredText formatting.
> Rs style guide

- themes/rtd/layout.html
- themes/rtd/layout_old.html
Upstream commit
https://github.com/snide/sphinx_rtd_theme/commit/a5e0e304d30ed7aa1eacc6cca04514913b8d2385
> Apply patch to fix search functionality

- cog-book/source/index.rst
- cog-book/source/sections/introducing_cog.rst
Brief update to feature points. Removed the images (not sure it added
anything constructive to the documentation) and added bullets to the
individual feature points. It would be nice to link these features to
actual DOCS on how these features work.
> Formatting updates to the introduction + index pages

- cog-book/source/sections/command_execution_rules.rst
resolves https://github.com/operable/cog/issues/1079
> add any all rules

- cog-book/source/references/relay_configuration.rst
- cog-book/source/sections/bootstrapping_cog.rst
- cog-book/source/sections/building_cog_from_scratch.rst
- cog-book/source/sections/bundle_configs.rst
- cog-book/source/sections/developing_a_trigger.rst
- cog-book/source/sections/dynamic_command_configuration.rst
- cog-book/source/sections/installation_guide.rst
- cog-book/source/sections/installing_and_managing_relays.rst
- cog-book/source/sections/installing_your_first_command_bundle.rst
- cog-book/source/sections/managing_bundles.rst
- cog-book/source/sections/permissions_and_rules.rst
- cog-book/source/sections/triggers.rst
- cog-book/source/sections/user_management.rst
- cog-book/source/sections/writing_a_command_bundle.rst
We rewrote cogctl in Python, and as a result, some command invocations
changed.
Fixes operable/cog#1367
> Update cogctl invocations

- docs/references/cog_server_configuration.html
Documentation for https://github.com/operable/cog/pull/1399
> Document the usage of COG_PIPELINE_TIMEOUT

- cog-book/source/sections/installation_guide.rst
> Missing backlash in multi-line bash command

- cog-book/source/references/greenbar_tags.rst
- cog-book/source/sections/dynamic_command_configuration.rst
Fix some formatting
- table header
- excessive backslashes & backticks
- add an example of a direct layer in a dynamic configuration section
> Minor format fixes
